### ISSUE TITLE
いいねはその都度トランザクションを発行するのではなく、一度web2 dbに保存しておき、月に一度ブロックチェーンにpushする形式に変えたい

### ISSUE THREAD

**Issue by hiroyaiyori** [team-tissis/cInsightFrontend#11]

**Comment by hiroyaiyori** [comment]
backend, smartcontractの変更も必要なのでこのissueに取り掛かる際は@iyoriに一度連絡ください

**Comment by katoatsushi** [comment]
メモ
https://github.com/ethereum/web3.py/blob/ffc004bd1e6433d8cc2ca20fcfa3c6d60f2f634c/docs/quickstart.rst

**Comment by Shion-0014** [comment]
pushするコードを叩くクライアントは，anvilのmsgSender=1みたいなやつで良い（適当な誰か）

**Comment by hidenoriwakiri** [comment]
This issue is closed since it is solved by the pull request just above.
