### ISSUE TITLE
[Bug] 付与された数以上の「いいね」を押せてしまう

### ISSUE THREAD

**Issue by hidenoriwakiri** [team-tissis/cInsightFrontend#30]
## 環境
- Frontend: 2a96b4e684c0803ab49ed95508953ec4156cd309

## 対処法
- 残りいいね数をスマコンから取得。
- DB に溜まっているいいね数と残りいいね数が一致した時点で、いいねボタンを押せなくする。

**Comment by hidenoriwakiri** [comment]
- 勉強会へのいいねに関しては、即修正。
- コメントへのいいねに関しては、DB の根本的な変更が必要なので、一旦保留。

**Comment by katoatsushi** [comment]
作業メモ
BackendとFrontendの修正が必要

**Comment by katoatsushi** [comment]
Backend: `fix/error-popup` (`bc80768b15569767bc2f98ba4904fe6d3f106718`)
Frontend: `feature/fetch_favo`(`1714e07b1c730b495a00be6a7a450b382cbb2676`)

**Comment by hidenoriwakiri** [comment]
解決したので、close。
