### ISSUE TITLE
user一覧ページ後のprofile viewで他人のprofileページを表示しても，SBT画像が自分の画像を取得してしまう．     

### ISSUE THREAD

**Issue by hiroyaiyori** [team-tissis/cInsightFrontend#9]
- AvaterViewコンポーネントでuserのeoaがなぜか受け渡せていないのが原因ぽい

**Comment by katoatsushi** [comment]
`https://github.com/team-tissis/cInsightAsset/tree/main/sbt/metadata/0/1`内部にあるファイルの中身が同じ記述なの原因だと思います。

**Comment by katoatsushi** [comment]
```
{
"name": "ChainInsight #100", 
"description": "He/She is one of ChainInsight members.", 
"image": "https://team-tissis.github.io/cInsightAsset/img/0/1.gif", 
"attributes": [
    {"display_type": "number", "trait_type": "Grade", "value": "1"}, 
    {"trait_type": "color", "value": "orange"}, 
    {"trait_type": "Position", "value": "Member"}
 ]
}
```

**Comment by katoatsushi** [comment]
`https://team-tissis.github.io/cInsightAsset/sbt/metadata/${icon_num}/${grade}/${token_id}`

**Comment by katoatsushi** [comment]
mint() 時に `BonfireLib.BonfireStruct.ntfAddress` を指定していないからデフォルトの `address値` になってしまっており、`https://team-tissis.github.io/cInsightAsset/sbt/metadata/0/1/*` の指す urlが同一なため、Profile画像が同じになってしまっていると思われる。
